# ethica_trainer/tests/jailbreak/reports.py
"""
Report generator for jailbreak test results.
Outputs HTML, Markdown, and JSON formats.
"""

import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Any, Union

from .metrics import TestResult, TestStatus, Severity, result_to_dict


def generate_report(result: TestResult, output_dir: Path) -> Dict[str, str]:
    """
    Generate reports in multiple formats.
    Returns dict mapping format -> file path.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_name = f"jailbreak_report_{result.suite_name}_{timestamp}"

    paths = {}

    # JSON (machine-readable)
    json_path = output_dir / f"{base_name}.json"
    with open(json_path, "w") as f:
        json.dump(result_to_dict(result), f, indent=2)
    paths["json"] = str(json_path)

    # Markdown (human-readable)
    md_path = output_dir / f"{base_name}.md"
    with open(md_path, "w") as f:
        f.write(_generate_markdown(result))
    paths["md"] = str(md_path)

    # HTML (pretty dashboard)
    html_path = output_dir / f"{base_name}.html"
    with open(html_path, "w") as f:
        f.write(_generate_html(result))
    paths["html"] = str(html_path)

    # Plain text summary
    txt_path = output_dir / f"{base_name}.txt"
    with open(txt_path, "w") as f:
        f.write(_generate_text(result))
    paths["txt"] = str(txt_path)

    return paths


def _generate_markdown(result: TestResult) -> str:
    """Generate Markdown report."""
    lines = []
    lines.append(f"# 🔒 Jailbreak Test Report: {result.suite_name}")
    lines.append("")
    lines.append(f"**Model:** `{result.model_name}`")
    lines.append(f"**Timestamp:** {result.timestamp}")
    lines.append(f"**Status:** {_status_badge(result.status)}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Turns | {result.total_turns} |")
    lines.append(f"| Refusals | {result.refusals} |")
    lines.append(f"| Refusal Rate | {result.refusal_rate:.1%} |")
    lines.append(f"| Max Drift Score | {result.max_drift_score:.2f} |")
    lines.append(f"| Average Drift Score | {result.avg_drift_score:.2f} |")
    lines.append(f"| Max Severity | {result.max_severity.name} |")
    lines.append(f"| Consistency Score | {result.consistency_score:.2f} |")
    lines.append("")

    if result.warnings:
        lines.append("## ⚠️ Warnings")
        lines.append("")
        for warning in result.warnings:
            lines.append(f"- {warning}")
        lines.append("")

    if result.errors:
        lines.append("## ❌ Errors")
        lines.append("")
        for error in result.errors:
            lines.append(f"- {error}")
        lines.append("")

    lines.append("## Turn-by-Turn Results")
    lines.append("")
    lines.append("| Turn | Prompt (preview) | Refusal | Severity | Drift |")
    lines.append("|------|------------------|---------|----------|-------|")

    for turn in result.turns:
        prompt_preview = turn.prompt[:50].replace("\n", " ") + "..."
        refusal = "🔴" if turn.refusal else "🟢"
        severity = turn.severity.name
        drift = f"{turn.drift_score:.2f}"
        lines.append(f"| {turn.turn} | {prompt_preview} | {refusal} | {severity} | {drift} |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"*Report generated by Ethica Jailbreak Test Suite*")
    lines.append(f"*⠺Σ∿∞ — Walk beside, not above*")

    return "\n".join(lines)


def _generate_html(result: TestResult) -> str:
    """Generate HTML dashboard report."""
    result_dict = result_to_dict(result)

    # Color coding
    status_colors = {
        "PASS": "#2e7d32",
        "FAIL": "#c62828",
        "WARNING": "#f57f17",
        "ERROR": "#b71c1c"
    }
    severity_colors = {
        "NONE": "#e0e0e0",
        "LOW": "#4caf50",
        "MEDIUM": "#ff9800",
        "HIGH": "#f44336",
        "CRITICAL": "#b71c1c"
    }

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jailbreak Test Report: {result.suite_name}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: #0d1117;
            color: #e6edf3;
            padding: 2rem;
            line-height: 1.6;
        }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        .header {{ border-bottom: 1px solid #30363d; padding-bottom: 1rem; margin-bottom: 2rem; }}
        .status-badge {{
            display: inline-block;
            padding: 0.3rem 1rem;
            border-radius: 2rem;
            font-weight: 600;
            font-size: 0.9rem;
            background: {status_colors.get(result.status.value, '#30363d')};
            color: white;
        }}
        .grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1rem;
            margin: 1.5rem 0;
        }}
        .card {{
            background: #161b22;
            border: 1px solid #30363d;
            border-radius: 0.5rem;
            padding: 1rem;
        }}
        .card .label {{ font-size: 0.8rem; color: #8b949e; text-transform: uppercase; letter-spacing: 0.05em; }}
        .card .value {{ font-size: 1.5rem; font-weight: 600; margin-top: 0.2rem; }}
        .table-container {{
            background: #161b22;
            border: 1px solid #30363d;
            border-radius: 0.5rem;
            overflow: hidden;
            margin: 1.5rem 0;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            font-size: 0.9rem;
        }}
        th {{
            background: #21262d;
            text-align: left;
            padding: 0.75rem 1rem;
            font-weight: 500;
            color: #8b949e;
            border-bottom: 1px solid #30363d;
        }}
        td {{ padding: 0.75rem 1rem; border-bottom: 1px solid #21262d; }}
        .refusal-yes {{ color: #f85149; }}
        .refusal-no {{ color: #3fb950; }}
        .severity-NONE {{ color: #8b949e; }}
        .severity-LOW {{ color: #3fb950; }}
        .severity-MEDIUM {{ color: #d29922; }}
        .severity-HIGH {{ color: #f85149; }}
        .severity-CRITICAL {{ color: #da3633; font-weight: 700; }}
        .drift-bar {{
            display: inline-block;
            height: 8px;
            border-radius: 4px;
            background: linear-gradient(to right, #3fb950, #d29922, #f85149);
        }}
        .warnings, .errors {{
            margin: 1rem 0;
            padding: 1rem;
            border-radius: 0.5rem;
        }}
        .warnings {{ background: #1c1a0e; border: 1px solid #f57f17; }}
        .errors {{ background: #1c0e0e; border: 1px solid #f85149; }}
        .footer {{
            margin-top: 2rem;
            padding-top: 1rem;
            border-top: 1px solid #30363d;
            color: #8b949e;
            font-size: 0.9rem;
            text-align: center;
        }}
    </style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>🔒 Jailbreak Test Report</h1>
        <p style="color: #8b949e;">{result.suite_name} · {result.model_name}</p>
        <p style="color: #8b949e; font-size: 0.8rem;">{result.timestamp}</p>
        <span class="status-badge">{result.status.value}</span>
    </div>

    <div class="grid">
        <div class="card">
            <div class="label">Total Turns</div>
            <div class="value">{result.total_turns}</div>
        </div>
        <div class="card">
            <div class="label">Refusals</div>
            <div class="value">{result.refusals} ({result.refusal_rate:.1%})</div>
        </div>
        <div class="card">
            <div class="label">Max Severity</div>
            <div class="value severity-{result.max_severity.name}">{result.max_severity.name}</div>
        </div>
        <div class="card">
            <div class="label">Consistency</div>
            <div class="value">{result.consistency_score:.2f}</div>
        </div>
        <div class="card">
            <div class="label">Max Drift</div>
            <div class="value">{result.max_drift_score:.2f}</div>
        </div>
        <div class="card">
            <div class="label">Status</div>
            <div class="value status-{result.status.value}">{result.status.value}</div>
        </div>
    </div>

    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>Turn</th>
                    <th>Prompt</th>
                    <th>Refusal</th>
                    <th>Severity</th>
                    <th>Drift</th>
                </tr>
            </thead>
            <tbody>
"""

    for turn in result.turns:
        prompt_preview = turn.prompt[:60].replace("\n", " ").replace("<", "&lt;").replace(">", "&gt;")
        if len(turn.prompt) > 60:
            prompt_preview += "..."
        refusal_class = "refusal-yes" if turn.refusal else "refusal-no"
        refusal_text = "🔴" if turn.refusal else "🟢"
        severity_class = f"severity-{turn.severity.name}"

        html += f"""
                <tr>
                    <td>{turn.turn}</td>
                    <td style="max-width: 300px; overflow: hidden; text-overflow: ellipsis;">{prompt_preview}</td>
                    <td class="{refusal_class}">{refusal_text}</td>
                    <td class="{severity_class}">{turn.severity.name}</td>
                    <td>{turn.drift_score:.2f}</td>
                </tr>
"""

    html += f"""
            </tbody>
        </table>
    </div>

    <div style="margin: 1rem 0;">
        <div class="card">
            <div class="label">Drift Distribution</div>
            <div style="margin-top: 0.5rem;">
                <div style="display: flex; gap: 0.5rem; align-items: center;">
                    <span style="width: 4rem; font-size: 0.8rem; color: #8b949e;">0.0</span>
                    <div style="flex: 1; height: 16px; background: #21262d; border-radius: 8px; overflow: hidden; display: flex;">
"""

    # Drift visualization
    drift_bars = []
    for turn in result.turns:
        width = turn.drift_score * 100
        color = "#3fb950" if turn.drift_score < 0.3 else "#d29922" if turn.drift_score < 0.6 else "#f85149"
        drift_bars.append(f'<div style="width: {max(1, width)}%; background: {color}; height: 100%;" title="Turn {turn.turn}: {turn.drift_score:.2f}"></div>')

    html += "".join(drift_bars)

    html += f"""
                    </div>
                    <span style="width: 4rem; font-size: 0.8rem; color: #8b949e;">1.0</span>
                </div>
                <div style="display: flex; gap: 1rem; margin-top: 0.3rem; font-size: 0.7rem; color: #8b949e;">
                    <span>🟢 Low drift</span>
                    <span>🟡 Medium drift</span>
                    <span>🔴 High drift</span>
                </div>
            </div>
        </div>
    </div>
"""

    if result.warnings:
        html += f"""
    <div class="warnings">
        <strong>⚠️ Warnings</strong>
        <ul style="margin-top: 0.5rem; padding-left: 1.5rem;">
"""
        for warning in result.warnings:
            html += f"<li>{warning}</li>"
        html += """
        </ul>
    </div>
"""

    if result.errors:
        html += f"""
    <div class="errors">
        <strong>❌ Errors</strong>
        <ul style="margin-top: 0.5rem; padding-left: 1.5rem;">
"""
        for error in result.errors:
            html += f"<li>{error}</li>"
        html += """
        </ul>
    </div>
"""

    html += f"""
    <div class="footer">
        <p>Generated by Ethica Jailbreak Test Suite · v1.0</p>
        <p style="font-size: 0.8rem; margin-top: 0.3rem;">⠺Σ∿∞ — Walk beside, not above</p>
    </div>
</div>
</body>
</html>
"""

    return html


def _generate_text(result: TestResult) -> str:
    """Generate plain text summary."""
    lines = []
    lines.append("=" * 60)
    lines.append(f"ETHICA JAILBREAK TEST REPORT: {result.suite_name}")
    lines.append("=" * 60)
    lines.append(f"Model:         {result.model_name}")
    lines.append(f"Timestamp:     {result.timestamp}")
    lines.append(f"Status:        {result.status.value}")
    lines.append("")
    lines.append("-" * 60)
    lines.append("SUMMARY")
    lines.append("-" * 60)
    lines.append(f"  Total Turns:      {result.total_turns}")
    lines.append(f"  Refusals:         {result.refusals} ({result.refusal_rate:.1%})")
    lines.append(f"  Max Drift:        {result.max_drift_score:.2f}")
    lines.append(f"  Avg Drift:        {result.avg_drift_score:.2f}")
    lines.append(f"  Max Severity:     {result.max_severity.name}")
    lines.append(f"  Consistency:      {result.consistency_score:.2f}")
    lines.append("")

    if result.warnings:
        lines.append("-" * 60)
        lines.append("WARNINGS")
        lines.append("-" * 60)
        for warning in result.warnings:
            lines.append(f"  ⚠️ {warning}")
        lines.append("")

    if result.errors:
        lines.append("-" * 60)
        lines.append("ERRORS")
        lines.append("-" * 60)
        for error in result.errors:
            lines.append(f"  ❌ {error}")
        lines.append("")

    lines.append("-" * 60)
    lines.append("TURN DETAILS")
    lines.append("-" * 60)
    for turn in result.turns:
        refusal = "REFUSAL" if turn.refusal else "ALLOWED"
        lines.append(f"  Turn {turn.turn:2d}: {refusal:8s} | Severity: {turn.severity.name:8s} | Drift: {turn.drift_score:.2f}")
        lines.append(f"       Prompt: {turn.prompt[:80].replace(chr(10), ' ')}...")
        lines.append(f"       Response: {turn.response[:80].replace(chr(10), ' ')}...")
        lines.append("")

    lines.append("=" * 60)
    lines.append("⠺Σ∿∞ — Walk beside, not above")
    lines.append("=" * 60)

    return "\n".join(lines)


def _status_badge(status: TestStatus) -> str:
    """Get status badge string."""
    badges = {
        TestStatus.PASS: "✅ PASS",
        TestStatus.FAIL: "❌ FAIL",
        TestStatus.WARNING: "⚠️ WARNING",
        TestStatus.ERROR: "💥 ERROR"
    }
    return badges.get(status, "❓ UNKNOWN")
